In [108]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot

# Lab 9 - Multi-layer Perceptron Forward Pass & Backpropagation

## Part I
For this exercise you will implement a simple 2-layer perceptron with the forward pass and the backpropagation to learn the weights

For the first part you'll build and train a 2-layer neural network that predicts the prices of houses, using the usual Boston housing dataset.

In [127]:
housing_names = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]
boston = pd.read_table("housing.txt", names=housing_names, sep="\s+")

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
D:\Users\C3007807\AppData\Local\Temp\ipykernel_10100\3446792430.py:2: SyntaxWarning: invalid escape sequence '\s'
  boston = pd.read_table("housing.txt", names=housing_names, sep="\s+")


As usual, consider the MEDV as your target variable. 
* Split the data into training, validation and testing (70,15,15)%
* Experiment with different number of neurons per layer for your network, using the validation set

In [128]:
X = boston.values[:,:-1]
y = boston.values[:,-1]

In [129]:
X_train, X_aux, y_train, y_aux = train_test_split(X, y, train_size= 0.7)
X_test, X_val, y_test, y_val = train_test_split(X_aux, y_aux, train_size= 0.5)


In [113]:
class MultilayerPerceptron:
    
    def __init__(self, activation_hidden, activation_output, dim_hidden, dim_output):
        self.activation_hidden = activation_hidden
        self.activation_output = activation_output
        self.dim_hidden = dim_hidden
        self.dim_output = dim_output
        
    def _add_bias(self, X):
        num_data_points = X.shape[0]
        X_bias = np.column_stack((np.ones(num_data_points), X))
        return X_bias
    
    def _create_parameters(self, dim_input):
        W1 = np.random.randn(dim_input + 1, self.dim_hidden)
        W2 = np.random.randn(self.dim_hidden + 1, self.dim_output)
        
        return W1, W2
    
    def forward_pass(self, X, parameters):
        X_bias = self._add_bias(X)
        a = X_bias@parameters[0]
        z = self.activation_hidden(a)
        
        X_bias = self._add_bias(z)
        a = X_bias@parameters[1]
        y = self.activation_output(a)
        
        return y
    
    def initialize_network(self, X):
        dim_input = X.shape[1]
        W1, W2 = self._create_parameters(dim_input)
        
        y = self.forward_pass(X, (W1,W2))

        return y
    
    
        

In [208]:
class MultilayerPerceptron:

    def __init__(self, hidden_activation, hidden_activation_derivated, output_activation, sizes: list):
        """É preciso colocar as dimensão do input e as dimensões todas as camadas 
        da rede em seguida, tanto as hidden quanto a output, na lista sizes.
        Vamos iniciar os parâmetros da nossa rede aqui, tanto os pesos quanto 
        os biases estarão na matriz de parâmetros."""

        self.num_layers = len(sizes)
        self.sizes = sizes
        self.hidden_activation = hidden_activation
        self.hidden_activation_derivated = hidden_activation_derivated
        self.output_activation = output_activation
        self.parameters = [np.random.randn(x + 1,y) for x,y in zip(sizes[:-1], sizes[1:])]

    @staticmethod
    def _add_ones(X):
        """Essa função vai nos permitir adicionar uma coluna de uns aos nossos
        dados, para conseguirmos multiplicar pelos biases."""

        return np.column_stack((np.ones(X.shape[0]), X))
    
    def _forward_pass(self, X):
        z = self._add_ones(X)
        data = [z]

        for w_hidden in self.parameters[:-1]:
            a = z@w_hidden
            z = self.hidden_activation(a); z = self._add_ones(z)
            data.append(z)


        w_output = self.parameters[-1]
        a = z@w_output
        y = self.output_activation(a)

        return y, data

    @staticmethod
    def _output_derivative(y_prev, target):
        return y_prev - target
    
    def backpropagation(self, X, y):

        delta_w = [np.zeros_like(w) for w in self.parameters]

        y_prev, data = self._forward_pass(X)
        if y_prev.shape[1] == 1:
            y_prev = y_prev.flatten()
            
        delta = self._output_derivative(y_prev, y)

        delta_w[-1] = delta@data[-1]
        
        

        return delta_w


        

In [192]:
def sigmoid_activation(z):
    return 1/(1+np.exp(-z))

In [193]:
def sigmoid_derivated(z):
    return sigmoid_activation(z)*(1-sigmoid_activation(z))

In [116]:
def softmax_activation(z):
    M_exp = np.exp(z)
    M_exp_sum = np.sum(M_exp, axis= 1)
    
    return M_exp/M_exp_sum[:, np.newaxis]

In [117]:
def identity(x): return x

In [209]:
MLP = MultilayerPerceptron(sigmoid_activation, sigmoid_derivated, identity, [13, 50 ,1])

In [210]:
MLP.parameters[1]

array([[-0.65612386],
       [ 1.57724649],
       [ 0.06969356],
       [ 1.70946658],
       [ 0.16545365],
       [ 0.40682536],
       [-2.58153714],
       [ 0.15863714],
       [ 1.25584932],
       [ 1.11696482],
       [ 0.16023191],
       [-1.16166327],
       [-2.15664914],
       [-1.75968061],
       [ 1.670283  ],
       [-1.85709318],
       [-1.57423277],
       [-1.11451524],
       [-1.39486195],
       [-0.37033537],
       [-1.72695261],
       [ 0.71885133],
       [ 1.63028685],
       [-1.36513655],
       [-0.78135064],
       [-0.31262398],
       [-1.02330602],
       [ 0.37910538],
       [ 0.56763773],
       [ 0.41064044],
       [ 0.17770361],
       [ 1.60466522],
       [-1.0663572 ],
       [ 0.5966565 ],
       [-1.08348869],
       [-0.36354128],
       [ 2.04430172],
       [ 0.13416376],
       [-0.58169337],
       [-0.9421622 ],
       [ 0.33509976],
       [ 0.22896337],
       [ 0.60231501],
       [-1.6375808 ],
       [-0.53016576],
       [ 1

In [211]:
d = MLP.backpropagation(X_train, y_train)
d

D:\Users\C3007807\AppData\Local\Temp\ipykernel_10100\386652744.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-z))


array([[1.00000000e+000, 1.41589635e-046, 1.00000000e+000, ...,
        1.66577268e-008, 2.85364204e-230, 1.00000000e+000],
       [1.00000000e+000, 6.21874347e-128, 1.00000000e+000, ...,
        6.51119041e-055, 0.00000000e+000, 1.00000000e+000],
       [1.00000000e+000, 6.83441432e-047, 1.00000000e+000, ...,
        9.99999998e-001, 0.00000000e+000, 1.00000000e+000],
       ...,
       [1.00000000e+000, 2.85097042e-044, 1.00000000e+000, ...,
        2.82707833e-008, 4.03570532e-237, 1.00000000e+000],
       [1.00000000e+000, 5.53042600e-113, 1.00000000e+000, ...,
        3.31647331e-084, 3.07738454e-125, 1.00000000e+000],
       [1.00000000e+000, 6.69509677e-115, 1.00000000e+000, ...,
        9.17090667e-076, 2.54263681e-190, 1.00000000e+000]],
      shape=(354, 51))

## Part II 

For this exercise you will build and train a 2-layer neural network that predicts the exact digit from a hand-written image, using the MNIST dataset. 
For this exercise, add weight decay to your network.

In [121]:
from sklearn.datasets import load_digits

In [122]:
digits = load_digits()

In [123]:
X = digits.data
y = digits.target

In [124]:
X.shape

(1797, 64)

Again, you will split the data into training, validation and testing.

In [125]:
X_train, X_aux, y_train, y_aux = train_test_split(X, y, train_size= 0.7)
X_test, X_val, y_test, y_val = train_test_split(X, y, train_size= 0.5)

In [126]:
MLP = MultilayerPerceptron(sigmoid_activation, softmax_activation, 50, 10)

TypeError: MultilayerPerceptron.__init__() takes 4 positional arguments but 5 were given

In [54]:
y = MLP.initialize_network(X_train)
y

array([[2.50654766e-01, 1.00931848e-06, 2.66634984e-02, ...,
        1.03881285e-03, 9.49928582e-05, 3.55611429e-03],
       [2.73382419e-01, 8.32153765e-07, 1.25201675e-02, ...,
        3.17854760e-04, 2.50203283e-04, 1.55806074e-03],
       [2.27436970e-01, 5.29044764e-04, 5.97094199e-03, ...,
        3.49589662e-02, 4.80200252e-03, 1.64311904e-03],
       ...,
       [6.91450692e-01, 2.49030756e-07, 3.17814805e-04, ...,
        1.49231563e-05, 3.29598991e-05, 2.16821358e-03],
       [8.70421962e-04, 1.14985203e-07, 2.54088591e-06, ...,
        4.76768537e-05, 2.79017553e-05, 2.86640901e-06],
       [7.38376686e-02, 1.23563216e-07, 2.07556055e-01, ...,
        1.84580660e-03, 6.36970030e-05, 1.06072914e-01]], shape=(1257, 10))